/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __fastcall sub_15C(_DWORD, _DWORD, _DWORD, _DWORD); // weak
void __fastcall sub_44A(int a1, int a2);
void sub_474();
int __fastcall sub_6A4(int result, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8);
int __fastcall sub_88A(int result, int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8);
int __fastcall sub_978(int a1, int a2, int a3);
void __spoils<R1,R2,R3,R12> sub_988();
int sub_998();
int sub_9AC();
int sub_9C0();
int __fastcall sub_9D4(int a1, int a2, int a3);
int __fastcall sub_9E8(int a1, int a2, int a3);
unsigned int __fastcall sub_A4C(unsigned int a1, int a2);
int __fastcall sub_A8C(unsigned __int8 *a1);
void __noreturn sub_A9C();
void __fastcall sub_B38(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_B94(unsigned __int8 a1);
void sub_C40();
int sub_C90();
void sub_CA8();
int sub_CC0();
void __fastcall sub_103C(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_1164(char a1);
int __fastcall sub_1268(char a1);
void __fastcall sub_149C(int a1, int a2);
int __fastcall sub_1540(int result, char a2);
int __fastcall sub_1576(int result);
BOOL __fastcall sub_1594(int a1);
int __fastcall sub_15C2(int result);
int __fastcall sub_17D6(int a1);
int *__fastcall sub_185A(int *result, unsigned __int8 a2);
unsigned __int8 __fastcall sub_1878(unsigned __int8 result);
unsigned __int16 __fastcall sub_1898(unsigned __int16 result, unsigned __int16 a2);
int __fastcall sub_18D0(unsigned __int16 a1);
unsigned int *__fastcall sub_1A78(unsigned int *result, unsigned int *a2);
_DWORD *__fastcall sub_1B48(_DWORD *result, char a2);
int __fastcall sub_1B80(int result, unsigned __int16 a2);
BOOL __fastcall sub_1B9C(int a1);
int __fastcall sub_1C58(int result);
void sub_1C88();
BOOL sub_1D80();
int sub_1DB0();
BOOL __fastcall sub_1FC0(int a1, unsigned __int16 a2);
void sub_200E();
void sub_210C();
unsigned __int8 __fastcall sub_213C(unsigned __int8 result);
void sub_215C();
unsigned __int8 __fastcall sub_2194(unsigned __int8 result);
int __fastcall sub_21B4(int result, int a2);
int sub_2248();
int __fastcall sub_2264(int result);
int __fastcall sub_229C(int result);
char __fastcall sub_2344(char result);
int __fastcall sub_2568(int result, char a2);
int __fastcall sub_25A4(int result, char a2);
int __fastcall sub_2754(int result, __int16 a2, char a3);
int __fastcall sub_279A(int result, __int16 a2);
int __fastcall sub_27B6(int a1);
_WORD *__fastcall sub_2C40(_WORD *result, char a2);
int __fastcall sub_2C7E(int result, char a2);
int __fastcall sub_2D44(int result, __int16 a2);
int __fastcall sub_2D60(int result, __int16 a2);
BOOL __fastcall sub_2D7C(int a1, unsigned __int16 a2);
_DWORD *__fastcall sub_32CC(_DWORD *a1);
int sub_3498();
int sub_34A4();
int sub_34BC();
int __fastcall sub_3676(int a1, unsigned __int16 a2, unsigned __int16 a3, int a4, int a5, int a6);
void __fastcall __noreturn sub_3D40(int a1, int a2);
void __fastcall sub_3E88(__int16 a1, int a2, __int64 a3);
void sub_5648();
void sub_56AC();
int __fastcall sub_56C4(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_5B6C(unsigned __int16 a1, unsigned __int16 a2, unsigned __int8 a3, unsigned __int16 a4);
void sub_5CF0();
int __fastcall sub_618C(__int16 a1, int a2, _BYTE *a3, unsigned __int16 a4, unsigned __int16 a5, unsigned __int8 a6, unsigned __int8 a7);
int __fastcall sub_639C(int result);
int __fastcall sub_63BC(unsigned __int8 a1);
int __fastcall sub_6464(unsigned __int8 a1);
int __fastcall sub_64A4(unsigned __int16 a1, unsigned __int16 a2, unsigned __int16 a3, unsigned __int16 a4);
int __fastcall sub_674C(unsigned __int8 a1);
int sub_6848();
int sub_6994();
int __fastcall sub_69B0(int result);
int __fastcall sub_6A98(int result);
int sub_7B44();
int __fastcall sub_7C5C(_WORD *a1, int a2, int a3, unsigned __int16 a4, _BYTE *a5);
void sub_7D58();
int sub_8144();
int sub_815C();
void sub_8314();
void __noreturn sub_8550();
_WORD *sub_855E();
void sub_8650();
void __noreturn sub_8660();
void sub_8798();
_BYTE *__fastcall sub_894C(int a1, __int16 a2, __int16 a3);
_DWORD *__fastcall sub_89A0(int a1, int a2);
void sub_89CC();
int sub_89D8();
int sub_89F0();
_DWORD *__fastcall sub_8A6C(_DWORD *a1);
int __fastcall sub_8B36(_DWORD); // weak
int __fastcall nullsub_2(_DWORD); // weak
_BYTE *__fastcall sub_8B58(_BYTE *result, char a2, int a3);
int __fastcall sub_8B68(int result, int a2);
int __fastcall sub_8CB4(int a1);
void sub_8DC0();
int __fastcall sub_8DD0(_DWORD *a1, int a2);
int __fastcall sub_8EB6(unsigned __int8 *a1, int a2, int a3);
int __fastcall sub_8F80(_DWORD *a1, int a2, int a3, int a4);
int __fastcall sub_90A0(_DWORD *a1);
void sub_918C();
int sub_9198();
int __fastcall sub_945C(int a1, int a2, _DWORD *a3);
int __fastcall sub_9486(int a1, _DWORD *a2, unsigned __int8 *a3, int a4);
int __fastcall sub_9A38(_DWORD *a1);
int __fastcall sub_9A5C(_DWORD *a1);
int __fastcall sub_9A80(_DWORD *a1);
unsigned __int8 *__fastcall sub_9AA0(unsigned __int8 *a1, unsigned __int8 a2, int a3);
unsigned int __fastcall sub_9ABC(unsigned int result, char *a2, int a3);
int __fastcall sub_9B3C(int a1, int a2);
int sub_9B4C();
int sub_9B5C();
int sub_9B6C();
int sub_9B7C();
int sub_9B8C();
int __fastcall sub_9B9C(int a1);
int __fastcall sub_B54C(int result);
int sub_B65C();
_WORD *sub_B674();
char __fastcall sub_B76C(char result);
int sub_B84C();
int sub_B86C();
void __fastcall sub_B8D0(int a1, int a2);
int __fastcall sub_B944(int result, int a2, unsigned __int16 a3);
int __fastcall sub_BA40(int a1, int a2, unsigned __int16 a3);
int sub_BD60();
int __fastcall sub_BD7C(int result);
unsigned __int16 __fastcall sub_BE64(unsigned __int16 result, unsigned __int16 a2);
_DWORD *__fastcall sub_C090(_DWORD *result);
int __fastcall sub_C16C(int result);
int __fastcall sub_C1A0(int result);
int sub_C338();
int __fastcall sub_C38C(int a1);
int __fastcall sub_C548(int result, unsigned __int16 a2);
int __fastcall sub_C564(int result, unsigned __int16 a2);
unsigned __int8 __fastcall sub_C580(unsigned __int8 result);
unsigned __int8 __fastcall sub_C5A0(unsigned __int8 result);
int sub_C654();
int __fastcall sub_C670(int result);
int __fastcall sub_C6A8(int result);
int __fastcall sub_C884(int result, char a2);
int __fastcall sub_C8C0(int result, char a2);
int __fastcall sub_C938(int result, char a2);
int __fastcall sub_C974(int result, char a2);
_WORD *__fastcall sub_CAAA(_WORD *result, char a2);
int __fastcall sub_CB4A(int a1);
BOOL __fastcall sub_CB62(int a1, unsigned __int16 a2);
int __fastcall sub_CB98(int a1);
_WORD *__fastcall sub_CEBC(_WORD *result, char a2);
int __fastcall sub_CF40(int result, __int16 a2);
int __fastcall sub_CFAE(int result, __int16 a2);
int __fastcall sub_D144(int result, char a2);
int __fastcall sub_D182(int result, __int16 a2);
BOOL __fastcall sub_D1A4(_WORD *a1, unsigned __int16 a2);
int sub_D1DA();
_WORD *sub_D258();
_WORD *sub_D2D6();
int __fastcall sub_D348(int result, unsigned int a2);
BOOL __fastcall sub_D660(unsigned __int8 a1);
BOOL __fastcall sub_D694(BOOL result);
int __fastcall sub_D758(unsigned int a1);
void sub_D790();
int sub_DA40();
int __fastcall sub_DC38(int a1, int a2);
int __fastcall sub_DC6A(unsigned __int8 a1);

//-------------------------------------------------------------------------
// Data declarations

int dword_7 = 8816127; // weak
int dword_B = 8818952; // weak
int dword_18 = 134252213; // weak
int dword_1F = -1; // weak
int dword_23 = -1; // weak
int dword_28 = -1; // weak
int dword_2C = 134252219; // weak
int dword_30 = 134252231; // weak
int dword_64 = 134220513; // weak
_UNKNOWN loc_8FC; // weak
_UNKNOWN loc_D18; // weak
_UNKNOWN loc_15E0; // weak
_UNKNOWN loc_160E; // weak
_UNKNOWN loc_1644; // weak
_UNKNOWN loc_17F0; // weak
int dword_1828 = -1; // weak
_UNKNOWN loc_1E48; // weak
_UNKNOWN loc_1FF2; // weak
int dword_211C[4] = { -1, -1, -1, -1 }; // weak
_UNKNOWN loc_252C; // weak
_UNKNOWN loc_27CE; // weak
int dword_2804 = -1; // weak
void *off_2A30 = (void *)0xB085B480; // weak
_UNKNOWN loc_2CC8; // weak
int dword_581C[4] = { -1, -1, -1, -1 }; // weak
_UNKNOWN loc_594C; // weak
int dword_6424[2] = { -1, -1 }; // weak
_UNKNOWN loc_64FC; // weak
_UNKNOWN loc_67C0; // weak
_UNKNOWN loc_6814; // weak
_UNKNOWN loc_6910; // weak
_UNKNOWN loc_69D4; // weak
int dword_7928 = -1; // weak
_UNKNOWN loc_7BDC; // weak
_UNKNOWN loc_7CEC; // weak
_UNKNOWN loc_7DAC; // weak
int dword_8104 = -1; // weak
int dword_8220[3] = { -1, -1, -1 }; // weak
_UNKNOWN loc_831A; // weak
_UNKNOWN loc_8378; // weak
_UNKNOWN loc_8730; // weak
char byte_8928[2] = { '\xFF', '\xFF' }; // weak
_UNKNOWN loc_89FC; // weak
int dword_8C00[2] = { -1, -1 }; // weak
_UNKNOWN loc_94AC; // weak
_UNKNOWN loc_B5A0; // weak
_UNKNOWN loc_B6F8; // weak
_UNKNOWN loc_B818; // weak
_UNKNOWN loc_B8FE; // weak
_UNKNOWN loc_B9C8; // weak
_UNKNOWN loc_BDA0; // weak
int dword_C11C[4] = { -1, -1, -1, -1 }; // weak
int dword_C324 = -1; // weak
_UNKNOWN loc_C3D0; // weak
_UNKNOWN loc_C8FC; // weak
int dword_CA24 = -1; // weak
_UNKNOWN loc_CBFE; // weak
_UNKNOWN loc_CDC4; // weak
_UNKNOWN loc_CEFA; // weak
_UNKNOWN loc_D5EC; // weak
_UNKNOWN loc_D7FE; // weak


//----- (0000044A) --------------------------------------------------------
void __fastcall sub_44A(int a1, int a2)
{
  int v6; // r11
  _DWORD *v7; // r1

  v7 = (_DWORD *)(a2 & 0x7FFFFFFF);
  if ( _ZF )
    __asm { SVCEQ           0xF091 }
  if ( _NF )
    *v7 = v6;
  MEMORY[0xFEC482A4](a1, v7);
  if ( _NF != _VF )
    __asm { SVCLT           0x8F381 }
  JUMPOUT(0x2A4);
}
// 2A0: control flows out of bounds to 2A4
// 294: variable '_ZF' is possibly undefined
// 298: variable '_NF' is possibly undefined
// 298: variable 'v6' is possibly undefined
// 2A0: variable '_VF' is possibly undefined

//----- (00000474) --------------------------------------------------------
void sub_474()
{
  JUMPOUT(0x242);
}
// 48E: control flows out of bounds to 242

//----- (000006A4) --------------------------------------------------------
int __fastcall sub_6A4(int result, unsigned int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8)
{
  bool v8; // cf
  int v9; // r4
  int v10; // r12
  bool v11; // zf
  int v12; // r5
  bool v13; // zf
  bool v14; // zf

  v11 = v9 == v10;
  v12 = v10 & (a4 >> 20);
  if ( v9 != v10 )
    v11 = v12 == v10;
  if ( v11 )
  {
    v14 = (result | (2 * a2)) == 0;
    if ( result | (2 * a2) )
    {
      v14 = (a3 | (2 * a4)) == 0;
    }
    else
    {
      result = a3;
      a2 = a4;
    }
    if ( !v14 && (v9 != v10 || !(result | (a2 << 12))) && (v12 != v10 || !(a3 | (a4 << 12))) )
      JUMPOUT(0x700);
    __asm { POP             {R4-R6,PC} }
  }
  v13 = (result | (2 * a2)) == 0;
  if ( result | (2 * a2) )
    v13 = (a3 | (2 * a4)) == 0;
  if ( v13 )
    JUMPOUT(0x6C0);
  if ( v9 )
    goto LABEL_28;
  while ( 1 )
  {
    v8 = __CFSHL__(result, 1);
    result *= 2;
    a2 += v8 + a2;
    if ( (a2 & 0x100000) != 0 )
      break;
    --v9;
  }
  if ( !v12 )
  {
LABEL_28:
    while ( 1 )
    {
      v8 = __CFSHL__(a3, 1);
      a3 *= 2;
      a4 += v8 + a4;
      if ( (a4 & 0x100000) != 0 )
        break;
      --v12;
    }
  }
  return result;
}
// 6BE: control flows out of bounds to 6C0
// 6FC: control flows out of bounds to 700
// 6A4: variable 'v9' is possibly undefined
// 6A4: variable 'v10' is possibly undefined

//----- (0000088A) --------------------------------------------------------
int __fastcall sub_88A(int result, int a2, int a3, unsigned int a4, int a5, int a6, int a7, int a8)
{
  bool v8; // cf
  int v9; // r4
  int v10; // r12
  int v11; // r5
  bool v12; // zf
  bool v13; // zf

  v11 = v10 & (a4 >> 20);
  v12 = v9 == v10;
  if ( v9 == v10 )
    v12 = v11 == v10;
  if ( v12 )
LABEL_27:
    __asm { POP             {R4-R6,PC} }
  if ( v9 == v10 )
  {
    if ( result | (a2 << 12) || v11 == v10 )
      goto LABEL_27;
LABEL_26:
    JUMPOUT(0x700);
  }
  if ( v11 == v10 )
  {
    if ( a3 | (a4 << 12) )
      goto LABEL_27;
    goto LABEL_25;
  }
  v13 = (result | (2 * a2)) == 0;
  if ( result | (2 * a2) )
    v13 = (a3 | (2 * a4)) == 0;
  if ( v13 )
  {
    if ( result | (2 * a2) )
      goto LABEL_26;
    if ( !(a3 | (2 * a4)) )
      goto LABEL_27;
LABEL_25:
    __asm { POP             {R4-R6,PC} }
  }
  if ( v9 )
    goto LABEL_30;
  while ( 1 )
  {
    v8 = __CFSHL__(result, 1);
    result *= 2;
    a2 += v8 + a2;
    if ( (a2 & 0x100000) != 0 )
      break;
    --v9;
  }
  if ( !v11 )
  {
LABEL_30:
    while ( 1 )
    {
      v8 = __CFSHL__(a3, 1);
      a3 *= 2;
      a4 += v8 + a4;
      if ( (a4 & 0x100000) != 0 )
        break;
      --v11;
    }
  }
  return result;
}
// 6FC: control flows out of bounds to 700
// 88A: variable 'v10' is possibly undefined
// 88E: variable 'v9' is possibly undefined

//----- (00000978) --------------------------------------------------------
int __fastcall sub_978(int a1, int a2, int a3)
{
  int result; // r0

  result = a3;
  sub_988();
  return result;
}

//----- (00000988) --------------------------------------------------------
void __spoils<R1,R2,R3,R12> sub_988()
{
  ((void (*)(void))loc_8FC)();
}

//----- (00000998) --------------------------------------------------------
int sub_998()
{
  char v0; // zf
  int result; // r0

  sub_988();
  if ( v0 )
    result = 1;
  else
    result = 0;
  return result;
}
// 9A0: variable 'v0' is possibly undefined

//----- (000009AC) --------------------------------------------------------
int sub_9AC()
{
  char v0; // cf
  int result; // r0

  sub_988();
  if ( v0 )
    result = 0;
  else
    result = 1;
  return result;
}
// 9B4: variable 'v0' is possibly undefined

//----- (000009C0) --------------------------------------------------------
int sub_9C0()
{
  char v0; // cf
  char v1; // zf
  int result; // r0

  sub_988();
  if ( !v1 & v0 )
    result = 0;
  else
    result = 1;
  return result;
}
// 9C8: variable 'v1' is possibly undefined
// 9C8: variable 'v0' is possibly undefined

//----- (000009D4) --------------------------------------------------------
int __fastcall sub_9D4(int a1, int a2, int a3)
{
  char v3; // cf
  char v4; // zf
  int result; // r0

  sub_978(a1, a2, a3);
  if ( !v4 & v3 )
    result = 0;
  else
    result = 1;
  return result;
}
// 9DC: variable 'v4' is possibly undefined
// 9DC: variable 'v3' is possibly undefined

//----- (000009E8) --------------------------------------------------------
int __fastcall sub_9E8(int a1, int a2, int a3)
{
  char v3; // cf
  int result; // r0

  sub_978(a1, a2, a3);
  if ( v3 )
    result = 0;
  else
    result = 1;
  return result;
}
// 9F0: variable 'v3' is possibly undefined

//----- (00000A4C) --------------------------------------------------------
unsigned int __fastcall sub_A4C(unsigned int a1, int a2)
{
  int v2; // r2
  bool v3; // cf
  int v4; // r2
  int v5; // r2

  v2 = 2 * a2;
  if ( __CFSHL__(a2, 1) )
    return 0;
  v3 = __CFADD__(v2, 0x200000);
  v4 = v2 + 0x200000;
  if ( !v3 )
  {
    if ( v4 < 0 )
    {
      v5 = -993 - (v4 >> 21);
      if ( v5 >= 0 )
        return ((a2 << 11) | 0x80000000 | (a1 >> 21)) >> v5;
      return -1;
    }
    return 0;
  }
  if ( !(a1 | (a2 << 12)) )
    return -1;
  return 0;
}

//----- (00000A8C) --------------------------------------------------------
int __fastcall sub_A8C(unsigned __int8 *a1)
{
  unsigned __int8 *v1; // r3

  v1 = a1;
  while ( *v1++ )
    ;
  return v1 - a1 - 1;
}

//----- (00000A9C) --------------------------------------------------------
void __noreturn sub_A9C()
{
  int i; // r1
  unsigned int j; // r2

  for ( i = 0; (unsigned int)(i + 0x20000000) < 0x200002D8; i += 4 )
    *(_DWORD *)(i + 0x20000000) = *(_DWORD *)(i + 134259756);
  for ( j = 536871640; j < 0x20001494; j += 4 )
    *(_DWORD *)j = 0;
  ((void (*)(void))loc_8730)();
  sub_8550();
}

//----- (00000B38) --------------------------------------------------------
void __fastcall sub_B38(int a1, int a2, int a3, int a4, int a5, int a6)
{
  int v6; // r7

  *(_BYTE *)(v6 + 20) = 1;
  sub_149C(1073816576, v6 + 4);
  sub_1540(1073816576, 1);
  sub_1576(1073816576);
  ((void (__fastcall *)(int))loc_7CEC)(10);
  while ( sub_1594(1073816576) )
    ;
  sub_15C2(1073816576);
  while ( ((int (__fastcall *)(int))loc_15E0)(1073816576) )
    ;
  ((void (__fastcall *)(int))loc_17F0)(1);
  __asm { POP             {R7,PC} }
}
// B3A: variable 'v6' is possibly undefined

//----- (00000B94) --------------------------------------------------------
int __fastcall sub_B94(unsigned __int8 a1)
{
  ((void (__fastcall *)(int, _DWORD, int, int))loc_1644)(1073816576, a1, 1, 7);
  ((void (__fastcall *)(int, int))loc_160E)(1073816576, 1);
  while ( !((int (__fastcall *)(int, int))dword_1828)(1073816576, 2) )
    ;
  sub_185A((int *)0x40012400, 2u);
  sub_185A((int *)0x40012400, 0x10u);
  return sub_17D6(1073816576);
}
// 1828: using guessed type int dword_1828;

//----- (00000C40) --------------------------------------------------------
void sub_C40()
{
  __int16 v0; // [sp+4h] [bp+4h] BYREF
  char v1; // [sp+6h] [bp+6h]
  char v2; // [sp+7h] [bp+7h]

  ((void (__fastcall *)(int, int))loc_252C)(17, 1);
  ((void (__fastcall *)(int))dword_211C[0])(1);
  sub_2344(0);
  sub_1878(0);
  v0 = 0x2000;
  v2 = 16;
  v1 = 2;
  ((void (__fastcall *)(int, __int16 *))loc_1E48)(1073811456, &v0);
  sub_200E();
}
// 211C: using guessed type int dword_211C[4];

//----- (00000C90) --------------------------------------------------------
int sub_C90()
{
  return ((int (__fastcall *)(int, int))loc_1FF2)(1073811456, 0x2000);
}

//----- (00000CA8) --------------------------------------------------------
void sub_CA8()
{
  sub_200E();
}

//----- (00000CC0) --------------------------------------------------------
int sub_CC0()
{
  unsigned __int8 i; // [sp+7h] [bp+7h]

  for ( i = 1; ; ++i )
  {
    if ( i > 0xCu )
    {
      if ( ((int (__fastcall *)(int))loc_D18)(101) != 1 )
        JUMPOUT(0xD00);
      JUMPOUT(0xD02);
    }
    if ( ((int (__fastcall *)(_DWORD))loc_D18)(i) != 1 )
      break;
  }
  return 0;
}
// CFE: control flows out of bounds to D00
// CFC: control flows out of bounds to D02

//----- (0000103C) --------------------------------------------------------
void __fastcall sub_103C(int a1, int a2, int a3, int a4, int a5, int a6)
{
  if ( sub_1FC0(1073809408, 0x8000u)
    && sub_1FC0(1073810432, 0x10u)
    && sub_1FC0(1073809408, 0x1000u)
    && sub_1FC0(1073810432, 0x20u)
    && sub_1FC0(1073810432, 8u)
    && sub_1FC0(1073810432, 0x40u)
    && sub_1FC0(1073809408, 0x800u)
    && sub_1FC0(1073810432, 0x400u)
    && !sub_1FC0(1073810432, 0x80u) )
  {
    MEMORY[0x20000230] = 1;
  }
  __asm { POP             {R7,PC} }
}

//----- (00001164) --------------------------------------------------------
int __fastcall sub_1164(char a1)
{
  if ( a1 )
  {
    MEMORY[0x20001024] = 0;
    MEMORY[0x200002FC] = 0;
  }
  if ( sub_1FC0(1073809408, 0x8000u) )
  {
    if ( sub_1FC0(1073809408, 0x8000u) )
    {
      MEMORY[0x20001024] = 0;
      MEMORY[0x200002FC] = 0;
    }
    return 0;
  }
  ((void (__fastcall *)(int))loc_7CEC)(5);
  if ( sub_1FC0(1073809408, 0x8000u) )
    return 0;
  MEMORY[0x200002FC] = MEMORY[0x20001024];
  return MEMORY[0x20001024];
}

//----- (00001268) --------------------------------------------------------
int __fastcall sub_1268(char a1)
{
  if ( a1 )
  {
    MEMORY[0x20001030] = 0;
    MEMORY[0x20000300] = 0;
  }
  if ( sub_1FC0(1073809408, 0x1000u) )
  {
    if ( sub_1FC0(1073809408, 0x1000u) )
    {
      MEMORY[0x20001030] = 0;
      MEMORY[0x20000300] = 0;
    }
    return 0;
  }
  ((void (__fastcall *)(int))loc_7CEC)(5);
  if ( sub_1FC0(1073809408, 0x1000u) )
    return 0;
  MEMORY[0x20000300] = MEMORY[0x20001030];
  return MEMORY[0x20001030];
}

//----- (0000149C) --------------------------------------------------------
void __fastcall sub_149C(int a1, int a2)
{
  *(_DWORD *)(a1 + 4) = (*(unsigned __int8 *)(a2 + 4) << 8) | *(_DWORD *)a2 | *(_DWORD *)(a1 + 4) & 0xFFF0FEFF;
  JUMPOUT(0x1500);
}
// 14FE: control flows out of bounds to 1500

//----- (00001540) --------------------------------------------------------
int __fastcall sub_1540(int result, char a2)
{
  if ( a2 )
    *(_DWORD *)(result + 8) |= 1u;
  else
    *(_DWORD *)(result + 8) &= 0xFFFFFFFE;
  return result;
}

//----- (00001576) --------------------------------------------------------
int __fastcall sub_1576(int result)
{
  *(_DWORD *)(result + 8) |= 8u;
  return result;
}

//----- (00001594) --------------------------------------------------------
BOOL __fastcall sub_1594(int a1)
{
  return (*(_DWORD *)(a1 + 8) & 8) != 0;
}

//----- (000015C2) --------------------------------------------------------
int __fastcall sub_15C2(int result)
{
  *(_DWORD *)(result + 8) |= 4u;
  return result;
}

//----- (000017D6) --------------------------------------------------------
int __fastcall sub_17D6(int a1)
{
  return (unsigned __int16)*(_DWORD *)(a1 + 76);
}

//----- (0000185A) --------------------------------------------------------
int *__fastcall sub_185A(int *result, unsigned __int8 a2)
{
  *result = ~a2;
  return result;
}

//----- (00001878) --------------------------------------------------------
unsigned __int8 __fastcall sub_1878(unsigned __int8 result)
{
  MEMORY[0x420D8600] = result;
  return result;
}

//----- (00001898) --------------------------------------------------------
unsigned __int16 __fastcall sub_1898(unsigned __int16 result, unsigned __int16 a2)
{
  *(_DWORD *)(result + 0x40006C00) = a2;
  return result;
}

//----- (000018D0) --------------------------------------------------------
int __fastcall sub_18D0(unsigned __int16 a1)
{
  return *(unsigned __int16 *)(a1 + 0x40006C00);
}

//----- (00001A78) --------------------------------------------------------
unsigned int *__fastcall sub_1A78(unsigned int *result, unsigned int *a2)
{
  *result = a2[10] | a2[2] | a2[8] | a2[4] | a2[5] | a2[6] | a2[7] | a2[9] | *result & 0xFFFF800F;
  result[1] = a2[3];
  result[2] = *a2;
  result[3] = a2[1];
  return result;
}

//----- (00001B48) --------------------------------------------------------
_DWORD *__fastcall sub_1B48(_DWORD *result, char a2)
{
  if ( a2 )
    *result |= 1u;
  else
    *result &= 0xFFFEu;
  return result;
}

//----- (00001B80) --------------------------------------------------------
int __fastcall sub_1B80(int result, unsigned __int16 a2)
{
  *(_DWORD *)(result + 4) = a2;
  return result;
}

//----- (00001B9C) --------------------------------------------------------
BOOL __fastcall sub_1B9C(int a1)
{
  int v2; // [sp+8h] [bp+8h]

  if ( (a1 & 0x10000000) != 0 )
    v2 = MEMORY[0x40020400];
  else
    v2 = MEMORY[0x40020000];
  return (a1 & v2) != 0;
}

//----- (00001C58) --------------------------------------------------------
int __fastcall sub_1C58(int result)
{
  MEMORY[0x40022000] &= 0xFFFFFFEF;
  MEMORY[0x40022000] |= result;
  return result;
}

//----- (00001C88) --------------------------------------------------------
void sub_1C88()
{
  MEMORY[0x40022004] = -839939669;
}

//----- (00001D80) --------------------------------------------------------
BOOL sub_1D80()
{
  return (MEMORY[0x4002201C] & 2) != 0;
}

//----- (00001DB0) --------------------------------------------------------
int sub_1DB0()
{
  return 4;
}

//----- (00001FC0) --------------------------------------------------------
BOOL __fastcall sub_1FC0(int a1, unsigned __int16 a2)
{
  return (a2 & *(_DWORD *)(a1 + 8)) != 0;
}

//----- (0000200E) --------------------------------------------------------
void sub_200E()
{
  JUMPOUT(0x201C);
}
// 201A: control flows out of bounds to 201C

//----- (0000210C) --------------------------------------------------------
void sub_210C()
{
  __wfi();
}

//----- (0000213C) --------------------------------------------------------
unsigned __int8 __fastcall sub_213C(unsigned __int8 result)
{
  MEMORY[0x420E00A0] = result;
  return result;
}

//----- (0000215C) --------------------------------------------------------
void sub_215C()
{
  MEMORY[0x40007000] |= 4u;
  MEMORY[0x40007000] |= 2u;
  MEMORY[0xE000ED10] |= 4u;
  sub_210C();
}

//----- (00002194) --------------------------------------------------------
unsigned __int8 __fastcall sub_2194(unsigned __int8 result)
{
  MEMORY[0x42420000] = result;
  return result;
}

//----- (000021B4) --------------------------------------------------------
int __fastcall sub_21B4(int result, int a2)
{
  MEMORY[0x40021004] = a2 | result | MEMORY[0x40021004] & 0xFFC0FFFF;
  return result;
}

//----- (00002248) --------------------------------------------------------
int sub_2248()
{
  return MEMORY[0x40021004] & 0xC;
}

//----- (00002264) --------------------------------------------------------
int __fastcall sub_2264(int result)
{
  MEMORY[0x40021004] = result | MEMORY[0x40021004] & 0xFFFFFF0F;
  return result;
}

//----- (0000229C) --------------------------------------------------------
int __fastcall sub_229C(int result)
{
  MEMORY[0x40021004] = result | MEMORY[0x40021004] & 0xFFFFF8FF;
  return result;
}

//----- (00002344) --------------------------------------------------------
char __fastcall sub_2344(char result)
{
  MEMORY[0x40021020] = 0;
  if ( result == 1 )
  {
    MEMORY[0x40021020] = 1;
  }
  else if ( result == 4 )
  {
    MEMORY[0x40021020] = 5;
  }
  return result;
}

//----- (00002568) --------------------------------------------------------
int __fastcall sub_2568(int result, char a2)
{
  if ( a2 )
    MEMORY[0x4002101C] |= result;
  else
    MEMORY[0x4002101C] &= ~result;
  return result;
}

//----- (000025A4) --------------------------------------------------------
int __fastcall sub_25A4(int result, char a2)
{
  if ( a2 )
    MEMORY[0x4002100C] |= result;
  else
    MEMORY[0x4002100C] &= ~result;
  return result;
}

//----- (00002754) --------------------------------------------------------
int __fastcall sub_2754(int result, __int16 a2, char a3)
{
  if ( a3 )
    *(_WORD *)(result + 4) |= a2;
  else
    *(_WORD *)(result + 4) &= ~a2;
  return result;
}

//----- (0000279A) --------------------------------------------------------
int __fastcall sub_279A(int result, __int16 a2)
{
  *(_WORD *)(result + 12) = a2;
  return result;
}

//----- (000027B6) --------------------------------------------------------
int __fastcall sub_27B6(int a1)
{
  return *(unsigned __int16 *)(a1 + 12);
}

//----- (00002C40) --------------------------------------------------------
_WORD *__fastcall sub_2C40(_WORD *result, char a2)
{
  if ( a2 )
    *result |= 1u;
  else
    *result &= 0xFFFEu;
  return result;
}

//----- (00002C7E) --------------------------------------------------------
int __fastcall sub_2C7E(int result, char a2)
{
  if ( a2 )
    *(_WORD *)(result + 68) = ~((unsigned int)~(*(unsigned __int16 *)(result + 68) << 17) >> 17);
  else
    *(_WORD *)(result + 68) &= 0x7FFFu;
  return result;
}

//----- (00002D44) --------------------------------------------------------
int __fastcall sub_2D44(int result, __int16 a2)
{
  *(_WORD *)(result + 36) = a2;
  return result;
}

//----- (00002D60) --------------------------------------------------------
int __fastcall sub_2D60(int result, __int16 a2)
{
  *(_WORD *)(result + 52) = a2;
  return result;
}

//----- (00002D7C) --------------------------------------------------------
BOOL __fastcall sub_2D7C(int a1, unsigned __int16 a2)
{
  return (a2 & *(_WORD *)(a1 + 16)) != 0 && (a2 & *(_WORD *)(a1 + 12)) != 0;
}

//----- (000032CC) --------------------------------------------------------
_DWORD *__fastcall sub_32CC(_DWORD *a1)
{
  sub_1B48(a1, 0);
  sub_1B80(1073872944, MEMORY[0x20001048]);
  return sub_1B48(a1, 1);
}

//----- (00003498) --------------------------------------------------------
int sub_3498()
{
  return sub_C90();
}

//----- (000034A4) --------------------------------------------------------
int sub_34A4()
{
  sub_2568(402653184, 1);
  return ((int (__fastcall *)(int))dword_211C[0])(1);
}
// 211C: invalid function type has been ignored
// 211C: using guessed type int dword_211C[4];

//----- (000034BC) --------------------------------------------------------
int sub_34BC()
{
  int v0; // r0

  v0 = ((int (*)(void))loc_64FC)();
  return ((int (__fastcall *)(int))loc_67C0)(v0);
}

//----- (00003676) --------------------------------------------------------
int __fastcall sub_3676(int a1, unsigned __int16 a2, unsigned __int16 a3, int a4, int a5, int a6)
{
  return ((int (__fastcall *)(int, int, _DWORD))loc_6910)(a1, a6 * a2 + a5, a3);
}

//----- (00003D40) --------------------------------------------------------
void __fastcall __noreturn sub_3D40(int a1, int a2)
{
  sub_15C(0, 0, a1, a2);
}
// 15C: using guessed type int __fastcall sub_15C(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00003E88) --------------------------------------------------------
void __fastcall sub_3E88(__int16 a1, int a2, __int64 a3)
{
  char v3; // nf
  int v4; // r7

  if ( !v3 )
  {
    *(_WORD *)(a2 + v4) = a1;
    *(_WORD *)(v4 + 251) = a1;
    JUMPOUT(0x3E98);
  }
  *(_QWORD *)v4 = a3;
  sub_3D40(*(_DWORD *)v4, *(_DWORD *)(v4 + 4));
}
// 3E96: control flows out of bounds to 3E98
// 3E88: variable 'v3' is possibly undefined
// 3E8A: variable 'v4' is possibly undefined

//----- (00005648) --------------------------------------------------------
void sub_5648()
{
  sub_8DC0();
  (*(void (__fastcall **)(_DWORD))byte_8928)(*(_DWORD *)(MEMORY[0x20000274] + 8));
  sub_200E();
  sub_CA8();
  sub_2568(402653184, 1);
  sub_213C(1u);
  MEMORY[0x40021000] &= 0xFFFEFFFF;
  MEMORY[0x40021000] &= 0xFFFBFFFF;
  sub_215C();
}

//----- (000056AC) --------------------------------------------------------
void sub_56AC()
{
  MEMORY[0x20000307] = 1;
}

//----- (000056C4) --------------------------------------------------------
int __fastcall sub_56C4(int a1, int a2, int a3, int a4, int a5)
{
  return a4 + (a5 - a4) * (a1 - a2) / (unsigned int)(a3 - a2);
}

//----- (00005B6C) --------------------------------------------------------
int __fastcall sub_5B6C(unsigned __int16 a1, unsigned __int16 a2, unsigned __int8 a3, unsigned __int16 a4)
{
  int i; // [sp+10h] [bp+10h]
  int v9; // [sp+14h] [bp+14h]
  int v10; // [sp+18h] [bp+18h]
  int v11; // [sp+1Ch] [bp+1Ch]

  v11 = 0;
  v10 = a3;
  v9 = 3 - 2 * a3;
  while ( v11 <= v10 )
  {
    for ( i = v11; i > 0; --i )
    {
      ((void (__fastcall *)(_DWORD, _DWORD, _DWORD))dword_581C[0])(
        (unsigned __int16)(a1 + v10),
        (unsigned __int16)(a2 - i),
        a4);
      ((void (__fastcall *)(_DWORD, _DWORD, _DWORD))dword_581C[0])(
        (unsigned __int16)(a1 - i),
        (unsigned __int16)(a2 + v10),
        a4);
    }
    if ( v10 > 0 )
      JUMPOUT(0x5C00);
    ++v11;
    if ( v9 >= 0 )
      v9 += 4 * (v11 - v10--) + 10;
    else
      v9 += 4 * v11 + 6;
  }
  return ((int (__fastcall *)(_DWORD, _DWORD, _DWORD))dword_581C[0])(a1, a2, a4);
}
// 5BFE: control flows out of bounds to 5C00
// 581C: using guessed type int dword_581C[4];

//----- (00005CF0) --------------------------------------------------------
void sub_5CF0()
{
  JUMPOUT(0x5D00);
}
// 5CFE: control flows out of bounds to 5D00

//----- (0000618C) --------------------------------------------------------
int __fastcall sub_618C(__int16 a1, int a2, _BYTE *a3, unsigned __int16 a4, unsigned __int16 a5, unsigned __int8 a6, unsigned __int8 a7)
{
  int v8; // [sp+0h] [bp-10h]
  int v9; // [sp+4h] [bp-Ch]
  int v10; // [sp+8h] [bp-8h]

  while ( *a3 )
  {
    v10 = a7;
    v9 = a6;
    v8 = a5;
    sub_5CF0();
    a1 += a6 >> 1;
    ++a3;
  }
  return ((int (__fastcall *)(_DWORD, _DWORD, _DWORD, int, int, int, int))loc_594C)(0, 0, a4, 1, v8, v9, v10);
}
// 61EA: variable 'v8' is possibly undefined
// 61EA: variable 'v9' is possibly undefined
// 61EA: variable 'v10' is possibly undefined

//----- (0000639C) --------------------------------------------------------
int __fastcall sub_639C(int result)
{
  int v2; // [sp+4h] [bp+4h]

  v2 = result;
  while ( v2-- )
    ;
  return result;
}

//----- (000063BC) --------------------------------------------------------
int __fastcall sub_63BC(unsigned __int8 a1)
{
  while ( !((int (__fastcall *)(int, int))loc_27CE)(1073819648, 2) )
    ;
  sub_279A(1073819648, a1);
  return sub_639C(1);
}

//----- (00006464) --------------------------------------------------------
int __fastcall sub_6464(unsigned __int8 a1)
{
  sub_200E();
  sub_200E();
  sub_63BC(a1);
  ((void (__fastcall *)(int, int))loc_1FF2)(1073809408, 8);
  return ((int (__fastcall *)(int, int))loc_1FF2)(1073809408, 16);
}

//----- (000064A4) --------------------------------------------------------
int __fastcall sub_64A4(unsigned __int16 a1, unsigned __int16 a2, unsigned __int16 a3, unsigned __int16 a4)
{
  sub_6464(0x2Au);
  ((void (__fastcall *)(_DWORD))dword_6424[0])(a1);
  ((void (__fastcall *)(_DWORD))dword_6424[0])(a3);
  sub_6464(0x2Bu);
  ((void (__fastcall *)(_DWORD))dword_6424[0])(a2);
  ((void (__fastcall *)(_DWORD))dword_6424[0])(a4);
  return sub_6464(0x2Cu);
}
// 6424: using guessed type int dword_6424[2];

//----- (0000674C) --------------------------------------------------------
int __fastcall sub_674C(unsigned __int8 a1)
{
  char v4; // [sp+Fh] [bp+Fh]
  char v5; // [sp+Fh] [bp+Fh]

  v4 = 0;
  while ( !((int (__fastcall *)(int, int))loc_27CE)(1073819648, 2) )
  {
    if ( (unsigned __int8)++v4 > 0xC8u )
      return 0;
  }
  sub_279A(1073819648, a1);
  v5 = 0;
  while ( !((int (__fastcall *)(int, int))loc_27CE)(1073819648, 1) )
  {
    if ( (unsigned __int8)++v5 > 0xC8u )
      return 0;
  }
  return (unsigned __int8)sub_27B6(1073819648);
}

//----- (00006848) --------------------------------------------------------
int sub_6848()
{
  unsigned __int16 v0; // r0
  unsigned __int16 v2; // [sp+6h] [bp+6h]

  MEMORY[0x42218188] = 0;
  sub_674C(0x90u);
  sub_674C(0);
  sub_674C(0);
  sub_674C(0);
  v2 = (unsigned __int16)sub_674C(0xFFu) << 8;
  v0 = sub_674C(0xFFu);
  MEMORY[0x42218188] = 1;
  return v2 | v0;
}

//----- (00006994) --------------------------------------------------------
int sub_6994()
{
  int result; // r0

  do
    result = ((int (*)(void))loc_6814)();
  while ( (result & 1) == 1 );
  return result;
}

//----- (000069B0) --------------------------------------------------------
int __fastcall sub_69B0(int result)
{
  MEMORY[0xE000ED0C] = result | 0x5FA0000;
  return result;
}

//----- (00006A98) --------------------------------------------------------
int __fastcall sub_6A98(int result)
{
  if ( result == 4 )
    MEMORY[0xE000E010] |= 4u;
  else
    MEMORY[0xE000E010] &= 0xFFFFFFFB;
  return result;
}

//----- (00007B44) --------------------------------------------------------
int sub_7B44()
{
  return ((int (__fastcall *)(int))dword_7928)(536875136);
}
// 7928: using guessed type int dword_7928;

//----- (00007C5C) --------------------------------------------------------
int __fastcall sub_7C5C(_WORD *a1, int a2, int a3, unsigned __int16 a4, _BYTE *a5)
{
  if ( ((int (__fastcall *)(_WORD *, int, int, _DWORD))loc_7BDC)(a1, a2, a3, a4) )
    return 0;
  *a5 = *(_BYTE *)(a3 + (unsigned __int16)*a1);
  *a1 = *a1 + 1 - a4 * (((unsigned __int16)*a1 + 1) / a4);
  return 1;
}

//----- (00007D58) --------------------------------------------------------
void sub_7D58()
{
  if ( MEMORY[0x20000260] == 61203 )
    MEMORY[0x200002F4] = (unsigned __int8)((int (*)(void))loc_7DAC)() == 254;
  else
    MEMORY[0x200002F4] = 0;
}

//----- (00008144) --------------------------------------------------------
int sub_8144()
{
  return MEMORY[0x2000100C];
}

//----- (0000815C) --------------------------------------------------------
int sub_815C()
{
  char v2[4]; // [sp+4h] [bp+4h] BYREF

  ((void (__fastcall *)(char *, _DWORD, int))dword_8104)(v2, MEMORY[0x2000100C], 1);
  if ( MEMORY[0x2000100C] >= MEMORY[0x20000270] )
    return 255;
  ++MEMORY[0x2000100C];
  v2[3] = v2[0];
  return (unsigned __int8)v2[0];
}
// 8104: using guessed type int dword_8104;

//----- (00008314) --------------------------------------------------------
void sub_8314()
{
  ((void (*)(void))((char *)&loc_831A + 2))();
  JUMPOUT(0x831E);
}
// 831A: control flows out of bounds to 831E

//----- (00008550) --------------------------------------------------------
void __noreturn sub_8550()
{
  sub_8314();
  while ( 1 )
    ((void (*)(void))loc_8378)();
}

//----- (0000855E) --------------------------------------------------------
_WORD *sub_855E()
{
  __int16 v1[6]; // [sp+4h] [bp+4h] BYREF
  char v2[6]; // [sp+10h] [bp+10h] BYREF
  __int16 v3; // [sp+16h] [bp+16h]

  v3 = 1000;
  sub_2568(1, 1);
  ((void (__fastcall *)(int))dword_2804)(0x40000000);
  v1[1] = 0;
  v1[3] = 0;
  v1[2] = 999;
  v1[0] = 63;
  ((void (__fastcall *)(int, __int16 *))off_2A30)(0x40000000, v1);
  v2[0] = 28;
  v2[1] = 10;
  v2[2] = 0;
  v2[3] = 1;
  ((void (__fastcall *)(char *))loc_69D4)(v2);
  sub_2D44(0x40000000, 0);
  ((void (__fastcall *)(int, int, int))loc_2CC8)(0x40000000, 1, 1);
  return sub_2C40((_WORD *)0x40000000, 1);
}
// 2804: using guessed type int dword_2804;
// 2A30: using guessed type void *off_2A30;

//----- (00008650) --------------------------------------------------------
void sub_8650()
{
  __dsb(0xFu);
}

//----- (00008660) --------------------------------------------------------
void __noreturn sub_8660()
{
  MEMORY[0xE000ED0C] = MEMORY[0xE000ED0C] & 0x700 | 0x5FA0004;
  sub_8650();
  while ( 1 )
    ;
}

//----- (00008798) --------------------------------------------------------
void sub_8798()
{
  ;
}

//----- (0000894C) --------------------------------------------------------
_BYTE *__fastcall sub_894C(int a1, __int16 a2, __int16 a3)
{
  _BYTE *result; // r0

  *(_DWORD *)a1 = 0;
  *(_DWORD *)(a1 + 4) = 0;
  *(_DWORD *)(a1 + 16) = 0;
  *(_DWORD *)(a1 + 20) = 0;
  *(int *)((char *)&dword_7 + a1 + 1) = 0;
  *(_WORD *)((char *)&dword_B + a1 + 1) = a2;
  *(int *)((char *)&dword_64 + a1) = 0;
  *(_WORD *)((char *)&dword_B + a1 + 3) = a3;
  *(int *)((char *)&dword_18 + a1) = 0;
  result = sub_8B58((_BYTE *)(a1 + 92), 0, 8);
  *(int *)((char *)&dword_1F + a1 + 1) = a1;
  *(int *)((char *)&dword_23 + a1 + 1) = 134254129;
  *(int *)((char *)&dword_28 + a1) = 134254163;
  *(int *)((char *)&dword_2C + a1) = 134254219;
  *(int *)((char *)&dword_30 + a1) = 134254255;
  return result;
}
// 7: using guessed type int dword_7;
// B: using guessed type int dword_B;
// 18: using guessed type int dword_18;
// 1F: using guessed type int dword_1F;
// 23: using guessed type int dword_23;
// 28: using guessed type int dword_28;
// 2C: using guessed type int dword_2C;
// 30: using guessed type int dword_30;
// 64: using guessed type int dword_64;

//----- (000089A0) --------------------------------------------------------
_DWORD *__fastcall sub_89A0(int a1, int a2)
{
  int v2; // r5
  _DWORD *v4; // r0
  _DWORD *v5; // r4
  _BYTE *v6; // r0

  v2 = 104 * (a2 - 1);
  v4 = (_DWORD *)((int (__fastcall *)(int, int))dword_8C00[0])(a1, v2 + 116);
  v5 = v4;
  if ( v4 )
  {
    *v4 = 0;
    v4[1] = a2;
    v6 = v4 + 3;
    v5[2] = v6;
    sub_8B58(v6, 0, v2 + 104);
  }
  return v5;
}
// 8C00: using guessed type int dword_8C00[2];

//----- (000089CC) --------------------------------------------------------
void sub_89CC()
{
  JUMPOUT(0x8B38);
}
// 89CE: control flows out of bounds to 8B38
// 8B36: using guessed type int sub_8B36();

//----- (000089D8) --------------------------------------------------------
int sub_89D8()
{
  return nullsub_2(536876174);
}
// 8B3A: using guessed type int __fastcall nullsub_2(_DWORD);

//----- (000089F0) --------------------------------------------------------
int sub_89F0()
{
  return nullsub_2(536876169);
}
// 8B3A: using guessed type int __fastcall nullsub_2(_DWORD);

//----- (00008A6C) --------------------------------------------------------
// local variable allocation has failed, the output may be wrong!
_DWORD *__fastcall sub_8A6C(_DWORD *a1)
{
  int v2; // r6
  int *v3; // r6
  int v4; // r3 OVERLAPPED
  _DWORD *v5; // r4 OVERLAPPED
  int v6; // r5

  sub_89CC();
  v2 = MEMORY[0x800A3D4];
  if ( !*(_DWORD *)(MEMORY[0x800A3D4] + 24) )
    ((void (__fastcall *)(_DWORD))loc_89FC)(MEMORY[0x800A3D4]);
  v3 = (int *)(v2 + 72);
  while ( 2 )
  {
    *(_QWORD *)&v4 = *(_QWORD *)(v3 + 1);
    while ( --v4 >= 0 )
    {
      v6 = *((__int16 *)v5 + 6);
      if ( !*((_WORD *)v5 + 6) )
      {
        v5[3] = -65535;
        v5[25] = v6;
        sub_8B36(v5 + 22);
        sub_89D8();
        v5[1] = v6;
        v5[2] = v6;
        v5[4] = v6;
        v5[5] = v6;
        *v5 = v6;
        v5[6] = v6;
        sub_8B58((_BYTE *)v5 + 92, v6, 8);
        v5[13] = v6;
        v5[14] = v6;
        v5[18] = v6;
        v5[19] = v6;
        return v5;
      }
      v5 += 26;
    }
    if ( *v3 || (v5 = sub_89A0((int)a1, 4), (*v3 = (int)v5) != 0) )
    {
      v3 = (int *)*v3;
      continue;
    }
    break;
  }
  sub_89D8();
  *a1 = 12;
  return v5;
}
// 8A6C: variables would overlap: r3.4 and r3.8
// 8A6C: variables would overlap: r4.4 and r3.8
// 8B36: using guessed type int __fastcall sub_8B36(_DWORD);

//----- (00008B58) --------------------------------------------------------
_BYTE *__fastcall sub_8B58(_BYTE *result, char a2, int a3)
{
  _BYTE *v3; // r3
  _BYTE *v4; // r2

  v3 = result;
  v4 = &result[a3];
  while ( v3 != v4 )
    *v3++ = a2;
  return result;
}

//----- (00008B68) --------------------------------------------------------
int __fastcall sub_8B68(int result, int a2)
{
  _DWORD *v2; // r5
  int v3; // r3
  int *v4; // r4
  int *v5; // r3
  int *v6; // r2
  int *v7; // r0
  int v8; // r1
  int v9; // r0
  int v10; // r3
  int v11; // r1

  v2 = (_DWORD *)result;
  if ( a2 )
  {
    v3 = *(_DWORD *)(a2 - 4);
    v4 = (int *)(a2 - 4);
    if ( v3 < 0 )
      v4 = (int *)((char *)v4 + v3);
    sub_918C();
    v5 = (int *)MEMORY[0x2000103C];
    if ( MEMORY[0x2000103C] )
    {
      if ( MEMORY[0x2000103C] <= (unsigned int)v4 )
      {
        do
        {
          v6 = v5;
          v5 = (int *)v5[1];
        }
        while ( v5 && v5 <= v4 );
        v7 = (int *)((char *)v6 + *v6);
        if ( v7 == v4 )
        {
          v8 = *v6 + *v4;
          *v6 = v8;
          if ( v5 == (int *)((char *)v6 + v8) )
          {
            v9 = *v5;
            v10 = v5[1];
            *v6 = v8 + v9;
            v6[1] = v10;
          }
        }
        else if ( v7 <= v4 )
        {
          if ( v5 == (int *)((char *)v4 + *v4) )
          {
            v11 = *v5;
            v5 = (int *)v5[1];
            *v4 += v11;
          }
          v4[1] = (int)v5;
          v6[1] = (int)v4;
        }
        else
        {
          *v2 = 12;
        }
      }
      else
      {
        if ( (int *)MEMORY[0x2000103C] == (int *)((char *)v4 + *v4) )
        {
          v5 = *(int **)(MEMORY[0x2000103C] + 4);
          *v4 += *MEMORY[0x2000103C];
        }
        v4[1] = (int)v5;
        MEMORY[0x2000103C] = v4;
      }
    }
    else
    {
      v4[1] = MEMORY[0x2000103C];
      MEMORY[0x2000103C] = v4;
    }
    result = sub_9198();
  }
  return result;
}

//----- (00008CB4) --------------------------------------------------------
int __fastcall sub_8CB4(int a1)
{
  int v1; // r4

  v1 = MEMORY[0x20000274];
  if ( MEMORY[0x20000274] && !*(_DWORD *)(MEMORY[0x20000274] + 24) )
    ((void (__fastcall *)(_DWORD))loc_89FC)(MEMORY[0x20000274]);
  return ((int (__fastcall *)(int, _DWORD, int))loc_94AC)(v1, *(_DWORD *)(v1 + 8), a1);
}

//----- (00008DC0) --------------------------------------------------------
void sub_8DC0()
{
  JUMPOUT(0x8CE4);
}
// 8DC6: control flows out of bounds to 8CE4

//----- (00008DD0) --------------------------------------------------------
int __fastcall sub_8DD0(_DWORD *a1, int a2)
{
  int result; // r0

  MEMORY[0x20001490] = 0;
  result = sub_9B9C(a2);
  if ( result == -1 )
  {
    if ( MEMORY[0x20001490] )
      *a1 = MEMORY[0x20001490];
  }
  return result;
}

//----- (00008EB6) --------------------------------------------------------
int __fastcall sub_8EB6(unsigned __int8 *a1, int a2, int a3)
{
  int v3; // r1
  unsigned __int8 *v4; // r4
  int v5; // r3
  int v6; // t1
  int v7; // r2
  int v8; // t1

  if ( !a3 )
    return 0;
  v3 = a2 - 1;
  v4 = &a1[a3];
  do
  {
    v6 = *a1++;
    v5 = v6;
    v8 = *(unsigned __int8 *)++v3;
    v7 = v8;
  }
  while ( v5 == v8 && a1 != v4 && v5 );
  return v5 - v7;
}

//----- (00008F80) --------------------------------------------------------
int __fastcall sub_8F80(_DWORD *a1, int a2, int a3, int a4)
{
  int result; // r0

  MEMORY[0x20001490] = 0;
  result = ((int (__fastcall *)(int, int, int))dword_8220[0])(a2, a3, a4);
  if ( result == -1 )
  {
    if ( MEMORY[0x20001490] )
      *a1 = MEMORY[0x20001490];
  }
  return result;
}
// 8220: using guessed type int dword_8220[3];

//----- (000090A0) --------------------------------------------------------
int __fastcall sub_90A0(_DWORD *a1)
{
  int result; // r0

  MEMORY[0x20001490] = 0;
  result = sub_9B7C();
  if ( result == -1 )
  {
    if ( MEMORY[0x20001490] )
      *a1 = MEMORY[0x20001490];
  }
  return result;
}

//----- (0000918C) --------------------------------------------------------
void sub_918C()
{
  JUMPOUT(0x8B38);
}
// 918E: control flows out of bounds to 8B38
// 8B36: using guessed type int sub_8B36();

//----- (00009198) --------------------------------------------------------
int sub_9198()
{
  return nullsub_2(536876170);
}
// 8B3A: using guessed type int __fastcall nullsub_2(_DWORD);

//----- (0000945C) --------------------------------------------------------
int __fastcall sub_945C(int a1, int a2, _DWORD *a3)
{
  int v3; // r3
  _BYTE *v4; // r3

  v3 = a3[2] - 1;
  a3[2] = v3;
  if ( v3 < 0 && (v3 < a3[6] || a2 == 10) )
    JUMPOUT(0x8EDC);
  v4 = (_BYTE *)(*a3)++;
  *v4 = a2;
  return a2;
}
// 9474: control flows out of bounds to 8EDC

//----- (00009486) --------------------------------------------------------
int __fastcall sub_9486(int a1, _DWORD *a2, unsigned __int8 *a3, int a4)
{
  unsigned __int8 *v6; // r4
  unsigned __int8 *v7; // r5
  int result; // r0
  int v9; // t1

  v6 = a3;
  v7 = &a3[a4];
  while ( v6 != v7 )
  {
    v9 = *v6++;
    result = sub_945C(a1, v9, a2);
    if ( result == -1 )
      return result;
  }
  return 0;
}

//----- (00009A38) --------------------------------------------------------
int __fastcall sub_9A38(_DWORD *a1)
{
  int result; // r0

  MEMORY[0x20001490] = 0;
  result = sub_9B8C();
  if ( result == -1 )
  {
    if ( MEMORY[0x20001490] )
      *a1 = MEMORY[0x20001490];
  }
  return result;
}

//----- (00009A5C) --------------------------------------------------------
int __fastcall sub_9A5C(_DWORD *a1)
{
  int result; // r0

  MEMORY[0x20001490] = 0;
  result = sub_9B5C();
  if ( result == -1 )
  {
    if ( MEMORY[0x20001490] )
      *a1 = MEMORY[0x20001490];
  }
  return result;
}

//----- (00009A80) --------------------------------------------------------
int __fastcall sub_9A80(_DWORD *a1)
{
  int result; // r0

  MEMORY[0x20001490] = 0;
  result = sub_9B6C();
  if ( result == -1 )
  {
    if ( MEMORY[0x20001490] )
      *a1 = MEMORY[0x20001490];
  }
  return result;
}

//----- (00009AA0) --------------------------------------------------------
unsigned __int8 *__fastcall sub_9AA0(unsigned __int8 *a1, unsigned __int8 a2, int a3)
{
  unsigned __int8 *v3; // r3
  unsigned __int8 *v4; // r2
  unsigned __int8 *result; // r0
  int v6; // r4

  v3 = a1;
  v4 = &a1[a3];
  while ( 1 )
  {
    result = v3;
    if ( v3 == v4 )
      break;
    v6 = *v3++;
    if ( v6 == a2 )
      return result;
  }
  return 0;
}

//----- (00009ABC) --------------------------------------------------------
unsigned int __fastcall sub_9ABC(unsigned int result, char *a2, int a3)
{
  char *v3; // r4
  char *v4; // r3
  unsigned int v5; // r3
  char v6; // t1
  int i; // r2
  char v8; // t1

  v3 = &a2[a3];
  if ( result > (unsigned int)a2 && (v4 = &a2[a3], (unsigned int)v3 > result) )
  {
    for ( i = a3 + result; i != result; --i )
    {
      v8 = *--v4;
      *(_BYTE *)(i - 1) = v8;
    }
  }
  else
  {
    v5 = result - 1;
    while ( a2 != v3 )
    {
      v6 = *a2++;
      *(_BYTE *)++v5 = v6;
    }
  }
  return result;
}

//----- (00009B3C) --------------------------------------------------------
int __fastcall sub_9B3C(int a1, int a2)
{
  int v2; // r3
  int result; // r0

  v2 = *(_DWORD *)(a2 - 4);
  result = v2 - 4;
  if ( v2 < 0 )
    result += *(_DWORD *)(a2 + result);
  return result;
}

//----- (00009B4C) --------------------------------------------------------
int sub_9B4C()
{
  int result; // r0

  result = -1;
  MEMORY[0x20001490] = 88;
  return result;
}

//----- (00009B5C) --------------------------------------------------------
int sub_9B5C()
{
  int result; // r0

  result = -1;
  MEMORY[0x20001490] = 88;
  return result;
}

//----- (00009B6C) --------------------------------------------------------
int sub_9B6C()
{
  int result; // r0

  result = 0;
  MEMORY[0x20001490] = 88;
  return result;
}

//----- (00009B7C) --------------------------------------------------------
int sub_9B7C()
{
  int result; // r0

  result = -1;
  MEMORY[0x20001490] = 88;
  return result;
}

//----- (00009B8C) --------------------------------------------------------
int sub_9B8C()
{
  int result; // r0

  result = -1;
  MEMORY[0x20001490] = 88;
  return result;
}

//----- (00009B9C) --------------------------------------------------------
int __fastcall sub_9B9C(int a1)
{
  int v1; // r3

  v1 = MEMORY[0x20001044];
  if ( !MEMORY[0x20001044] )
    v1 = 536876180;
  MEMORY[0x20001044] = a1 + v1;
  return v1;
}

//----- (0000B54C) --------------------------------------------------------
int __fastcall sub_B54C(int result)
{
  _R3 = result;
  __asm { MSR.W           MSP, R3 }
  return result;
}

//----- (0000B65C) --------------------------------------------------------
int sub_B65C()
{
  ((void (__fastcall *)(int, int))loc_C8FC)(402653184, 1);
  return sub_C580(1u);
}

//----- (0000B674) --------------------------------------------------------
_WORD *sub_B674()
{
  __int16 v1[10]; // [sp+0h] [bp+0h] BYREF
  __int16 v2; // [sp+14h] [bp+14h] BYREF
  char v3; // [sp+16h] [bp+16h]
  char v4; // [sp+17h] [bp+17h]

  sub_C8C0(4096, 1);
  sub_C8C0(4, 1);
  v2 = 224;
  v3 = 3;
  v4 = 24;
  ((void (__fastcall *)(int, __int16 *))loc_C3D0)(1073809408, &v2);
  sub_C548(1073809408, 0xA0u);
  v1[0] = 0;
  v1[1] = 260;
  v1[2] = 0;
  v1[3] = 0;
  v1[4] = 0;
  v1[5] = 512;
  v1[6] = 8;
  v1[7] = 0;
  v1[8] = 7;
  ((void (__fastcall *)(int, __int16 *))dword_CA24)(1073819648, v1);
  return sub_CAAA((_WORD *)0x40013000, 1);
}
// CA24: using guessed type int dword_CA24;

//----- (0000B76C) --------------------------------------------------------
char __fastcall sub_B76C(char result)
{
  MEMORY[0x40013000] &= 0xFFC7u;
  MEMORY[0x40013000] |= 8 * (result & 7);
  MEMORY[0x40013000] |= 0x40u;
  return result;
}

//----- (0000B84C) --------------------------------------------------------
int sub_B84C()
{
  int result; // r0

  MEMORY[0x42218188] = 0;
  result = ((int (__fastcall *)(int))loc_B6F8)(6);
  MEMORY[0x42218188] = 1;
  return result;
}

//----- (0000B86C) --------------------------------------------------------
int sub_B86C()
{
  unsigned __int16 v0; // r0
  unsigned __int16 v2; // [sp+6h] [bp+6h]

  MEMORY[0x42218188] = 0;
  ((void (__fastcall *)(int))loc_B6F8)(144);
  ((void (__fastcall *)(_DWORD))loc_B6F8)(0);
  ((void (__fastcall *)(_DWORD))loc_B6F8)(0);
  ((void (__fastcall *)(_DWORD))loc_B6F8)(0);
  v2 = (unsigned __int16)((int (__fastcall *)(int))loc_B6F8)(255) << 8;
  v0 = ((int (__fastcall *)(int))loc_B6F8)(255);
  MEMORY[0x42218188] = 1;
  return v2 | v0;
}

//----- (0000B8D0) --------------------------------------------------------
void __fastcall sub_B8D0(int a1, int a2)
{
  MEMORY[0x42218188] = 0;
  ((void (__fastcall *)(int))loc_B6F8)(3);
  ((void (__fastcall *)(_DWORD))loc_B6F8)(BYTE2(a2));
  ((void (__fastcall *)(_DWORD))((char *)&loc_B8FE + 2))(BYTE1(a2));
  JUMPOUT(0xB902);
}
// B8FE: control flows out of bounds to B902

//----- (0000B944) --------------------------------------------------------
int __fastcall sub_B944(int result, int a2, unsigned __int16 a3)
{
  int v5; // [sp+Ch] [bp+Ch]

  v5 = result;
  if ( a3 )
  {
    sub_BD60();
    MEMORY[0x42218188] = 0;
    ((void (__fastcall *)(int))loc_B6F8)(11);
    ((void (__fastcall *)(_DWORD))loc_B6F8)(BYTE2(a2));
    ((void (__fastcall *)(_DWORD))loc_B6F8)(BYTE1(a2));
    ((void (__fastcall *)(_DWORD))loc_B6F8)((unsigned __int8)a2);
    ((void (__fastcall *)(int))loc_B6F8)(255);
    ((void (__fastcall *)(int, _DWORD))loc_B5A0)(v5, a3);
    while ( !((int (__fastcall *)(int))dword_C11C[0])(32) )
      ;
    sub_C16C(32);
    MEMORY[0x42218188] = 1;
    result = sub_BD60();
  }
  return result;
}
// C11C: using guessed type int dword_C11C[4];

//----- (0000BA40) --------------------------------------------------------
int __fastcall sub_BA40(int a1, int a2, unsigned __int16 a3)
{
  int result; // r0
  unsigned __int16 v4; // [sp+6h] [bp+6h]
  int v5; // [sp+8h] [bp+8h]
  unsigned __int16 v7; // [sp+16h] [bp+16h]

  v5 = a2;
  v4 = a3;
  v7 = 256 - (unsigned __int8)a2;
  if ( a3 <= (unsigned int)v7 )
    v7 = a3;
  while ( 1 )
  {
    result = ((int (__fastcall *)(int, int, _DWORD))loc_B9C8)(a1, v5, v7);
    if ( v4 == v7 )
      break;
    a1 += v7;
    v5 += v7;
    v4 -= v7;
    if ( v4 <= 0x100u )
      v7 = v4;
    else
      v7 = 256;
  }
  return result;
}

//----- (0000BD60) --------------------------------------------------------
int sub_BD60()
{
  int result; // r0

  do
    result = ((int (*)(void))loc_B818)();
  while ( (result & 1) == 1 );
  return result;
}

//----- (0000BD7C) --------------------------------------------------------
int __fastcall sub_BD7C(int result)
{
  MEMORY[0xE000ED0C] = result | 0x5FA0000;
  return result;
}

//----- (0000BE64) --------------------------------------------------------
unsigned __int16 __fastcall sub_BE64(unsigned __int16 result, unsigned __int16 a2)
{
  *(_DWORD *)(result + 0x40006C00) = a2;
  return result;
}

//----- (0000C090) --------------------------------------------------------
_DWORD *__fastcall sub_C090(_DWORD *result)
{
  *result = 0;
  result[1] = 0;
  result[2] = 0;
  result[3] = 0;
  result[4] = 0;
  result[5] = 0;
  result[6] = 0;
  result[7] = 0;
  result[8] = 0;
  result[9] = 0;
  result[10] = 0;
  return result;
}

//----- (0000C16C) --------------------------------------------------------
int __fastcall sub_C16C(int result)
{
  if ( (result & 0x10000000) != 0 )
    MEMORY[0x40020404] = result;
  else
    MEMORY[0x40020004] = result;
  return result;
}

//----- (0000C1A0) --------------------------------------------------------
int __fastcall sub_C1A0(int result)
{
  MEMORY[0x40022000] = result | MEMORY[0x40022000] & 0x38;
  return result;
}

//----- (0000C338) --------------------------------------------------------
int sub_C338()
{
  if ( (MEMORY[0x4002200C] & 1) == 1 )
    return 1;
  if ( (MEMORY[0x4002200C] & 4) != 0 )
    return 2;
  if ( (MEMORY[0x4002200C] & 0x10) != 0 )
    return 3;
  return 4;
}

//----- (0000C38C) --------------------------------------------------------
int __fastcall sub_C38C(int a1)
{
  unsigned __int8 v3; // [sp+Fh] [bp+Fh]

  v3 = sub_C338();
  while ( v3 == 1 && a1 )
  {
    v3 = sub_C338();
    --a1;
  }
  if ( !a1 )
    v3 = 5;
  return v3;
}

//----- (0000C548) --------------------------------------------------------
int __fastcall sub_C548(int result, unsigned __int16 a2)
{
  *(_DWORD *)(result + 16) = a2;
  return result;
}

//----- (0000C564) --------------------------------------------------------
int __fastcall sub_C564(int result, unsigned __int16 a2)
{
  *(_DWORD *)(result + 20) = a2;
  return result;
}

//----- (0000C580) --------------------------------------------------------
unsigned __int8 __fastcall sub_C580(unsigned __int8 result)
{
  MEMORY[0x420E0020] = result;
  return result;
}

//----- (0000C5A0) --------------------------------------------------------
unsigned __int8 __fastcall sub_C5A0(unsigned __int8 result)
{
  MEMORY[0x42420000] = result;
  return result;
}

//----- (0000C654) --------------------------------------------------------
int sub_C654()
{
  return MEMORY[0x40021004] & 0xC;
}

//----- (0000C670) --------------------------------------------------------
int __fastcall sub_C670(int result)
{
  MEMORY[0x40021004] = result | MEMORY[0x40021004] & 0xFFFFFF0F;
  return result;
}

//----- (0000C6A8) --------------------------------------------------------
int __fastcall sub_C6A8(int result)
{
  MEMORY[0x40021004] = result | MEMORY[0x40021004] & 0xFFFFF8FF;
  return result;
}

//----- (0000C884) --------------------------------------------------------
int __fastcall sub_C884(int result, char a2)
{
  if ( a2 )
    MEMORY[0x40021014] |= result;
  else
    MEMORY[0x40021014] &= ~result;
  return result;
}

//----- (0000C8C0) --------------------------------------------------------
int __fastcall sub_C8C0(int result, char a2)
{
  if ( a2 )
    MEMORY[0x40021018] |= result;
  else
    MEMORY[0x40021018] &= ~result;
  return result;
}

//----- (0000C938) --------------------------------------------------------
int __fastcall sub_C938(int result, char a2)
{
  if ( a2 )
    MEMORY[0x4002100C] |= result;
  else
    MEMORY[0x4002100C] &= ~result;
  return result;
}

//----- (0000C974) --------------------------------------------------------
int __fastcall sub_C974(int result, char a2)
{
  if ( a2 )
    MEMORY[0x40021010] |= result;
  else
    MEMORY[0x40021010] &= ~result;
  return result;
}

//----- (0000CAAA) --------------------------------------------------------
_WORD *__fastcall sub_CAAA(_WORD *result, char a2)
{
  if ( a2 )
    *result |= 0x40u;
  else
    *result &= 0xFFBFu;
  return result;
}

//----- (0000CB4A) --------------------------------------------------------
int __fastcall sub_CB4A(int a1)
{
  return *(unsigned __int16 *)(a1 + 12);
}

//----- (0000CB62) --------------------------------------------------------
BOOL __fastcall sub_CB62(int a1, unsigned __int16 a2)
{
  return (a2 & *(_WORD *)(a1 + 8)) != 0;
}

//----- (0000CB98) --------------------------------------------------------
int __fastcall sub_CB98(int a1)
{
  int result; // r0

  switch ( a1 )
  {
    case 1073818624:
      sub_C938(2048, 1);
      result = sub_C938(2048, 0);
      break;
    case 1073741824:
      sub_C974(1, 1);
      result = sub_C974(1, 0);
      break;
    case 1073742848:
      sub_C974(2, 1);
      result = sub_C974(2, 0);
      break;
    case 1073743872:
      ((void (__fastcall *)(int, int))((char *)&loc_CBFE + 2))(4, 1);
      JUMPOUT(0xCC02);
    case 1073744896:
      sub_C974(8, 1);
      JUMPOUT(0xCC1C);
    default:
      JUMPOUT(0xCC26);
  }
  return result;
}
// CBFE: control flows out of bounds to CC02
// CC18: control flows out of bounds to CC1C
// CC12: control flows out of bounds to CC26

//----- (0000CEBC) --------------------------------------------------------
_WORD *__fastcall sub_CEBC(_WORD *result, char a2)
{
  if ( a2 )
    *result |= 1u;
  else
    *result &= 0xFFFEu;
  return result;
}

//----- (0000CF40) --------------------------------------------------------
int __fastcall sub_CF40(int result, __int16 a2)
{
  *(_WORD *)(result + 36) = a2;
  return result;
}

//----- (0000CFAE) --------------------------------------------------------
int __fastcall sub_CFAE(int result, __int16 a2)
{
  *(_WORD *)(result + 16) = ~a2;
  return result;
}

//----- (0000D144) --------------------------------------------------------
int __fastcall sub_D144(int result, char a2)
{
  if ( a2 )
    *(_WORD *)(result + 12) |= 0x2000u;
  else
    *(_WORD *)(result + 12) &= 0xDFFFu;
  return result;
}

//----- (0000D182) --------------------------------------------------------
int __fastcall sub_D182(int result, __int16 a2)
{
  *(_WORD *)(result + 4) = a2 & 0x1FF;
  return result;
}

//----- (0000D1A4) --------------------------------------------------------
BOOL __fastcall sub_D1A4(_WORD *a1, unsigned __int16 a2)
{
  return (a2 & *a1) != 0;
}

//----- (0000D1DA) --------------------------------------------------------
int sub_D1DA()
{
  return sub_BD7C(1536);
}

//----- (0000D258) --------------------------------------------------------
_WORD *sub_D258()
{
  __int16 v1[6]; // [sp+4h] [bp+4h] BYREF
  char v2[6]; // [sp+10h] [bp+10h] BYREF
  __int16 v3; // [sp+16h] [bp+16h]

  v3 = 1000;
  ((void (__fastcall *)(int, int))loc_C8FC)(1, 1);
  sub_CB98(0x40000000);
  v1[1] = 0;
  v1[3] = 0;
  v1[2] = 999;
  v1[0] = 63;
  ((void (__fastcall *)(int, __int16 *))loc_CDC4)(0x40000000, v1);
  v2[0] = 28;
  v2[1] = 10;
  v2[2] = 0;
  v2[3] = 1;
  ((void (__fastcall *)(char *))loc_BDA0)(v2);
  sub_CF40(0x40000000, 0);
  ((void (__fastcall *)(int, int, int))loc_CEFA)(0x40000000, 1, 1);
  return sub_CEBC((_WORD *)0x40000000, 1);
}

//----- (0000D2D6) --------------------------------------------------------
_WORD *sub_D2D6()
{
  ((void (__fastcall *)(int, int, _DWORD))loc_CEFA)(0x40000000, 1, 0);
  return sub_CEBC((_WORD *)0x40000000, 0);
}

//----- (0000D348) --------------------------------------------------------
int __fastcall sub_D348(int result, unsigned int a2)
{
  int v2; // r3
  int v4; // [sp+8h] [bp+8h]
  int v5; // [sp+Ch] [bp+Ch]
  unsigned int v6; // [sp+10h] [bp+10h]
  unsigned int i; // [sp+14h] [bp+14h]

  v6 = 1000000000;
  v5 = 0;
  v4 = 0;
  for ( i = 0; i <= 9; ++i )
  {
    v2 = v5++;
    *(_BYTE *)(v2 + result) = a2 / v6 + 48;
    a2 -= v6 * (a2 / v6);
    v6 /= 0xAu;
    if ( v4 == 0 && *(_BYTE *)(v5 - 1 + result) == 48 )
      v5 = 0;
    else
      ++v4;
  }
  return result;
}

//----- (0000D660) --------------------------------------------------------
BOOL __fastcall sub_D660(unsigned __int8 a1)
{
  BOOL result; // r0

  sub_D182(1073821696, a1);
  do
    result = sub_D1A4((_WORD *)0x40013800, 0x80u);
  while ( !result );
  return result;
}

//----- (0000D694) --------------------------------------------------------
BOOL __fastcall sub_D694(BOOL result)
{
  unsigned __int8 *i; // [sp+4h] [bp+4h]

  for ( i = (unsigned __int8 *)result; *i; ++i )
    result = sub_D660(*i);
  return result;
}

//----- (0000D758) --------------------------------------------------------
int __fastcall sub_D758(unsigned int a1)
{
  int v2; // [sp+Ch] [bp+Ch]

  if ( (a1 & 0x3FF) != 0 )
    v2 = (a1 >> 10) + 1;
  else
    v2 = a1 >> 10;
  return v2;
}

//----- (0000D790) --------------------------------------------------------
void sub_D790()
{
  BOOL v0; // r0

  MEMORY[0x20000064] = (unsigned int)(MEMORY[0x20000018] - 0x8000000) >> 12;
  MEMORY[0x20000068] = -(1 << ((unsigned int)(MEMORY[0x20000018] - 0x8000000) >> 12));
  MEMORY[0x2000006C] = (((int (*)(void))dword_C324)() & MEMORY[0x20000068]) != MEMORY[0x20000068];
  while ( 1 )
  {
    while ( !MEMORY[0x20000070] )
    {
      sub_D694(134276664);
      MEMORY[0x20000070] = 1;
    }
    if ( MEMORY[0x20000070] == 1 )
    {
      v0 = sub_D694(134276680);
      ((void (__fastcall *)(BOOL))((char *)&loc_D7FE + 2))(v0);
      JUMPOUT(0xD802);
    }
  }
}
// D7FE: control flows out of bounds to D802
// C324: using guessed type int dword_C324;

//----- (0000DA40) --------------------------------------------------------
int sub_DA40()
{
  __int16 v1; // [sp+4h] [bp+4h] BYREF
  char v2; // [sp+6h] [bp+6h]
  char v3; // [sp+7h] [bp+7h]

  sub_C8C0(8, 1);
  v3 = 16;
  v2 = 3;
  v1 = 256;
  ((void (__fastcall *)(int, __int16 *))loc_C3D0)(1073810432, &v1);
  sub_C564(1073810432, 0x100u);
  v1 = 2048;
  ((void (__fastcall *)(int, __int16 *))loc_C3D0)(1073810432, &v1);
  sub_C548(1073810432, 0x800u);
  v1 = 0x2000;
  ((void (__fastcall *)(int, __int16 *))loc_C3D0)(1073810432, &v1);
  return sub_C548(1073810432, 0x2000u);
}

//----- (0000DC38) --------------------------------------------------------
int __fastcall sub_DC38(int a1, int a2)
{
  while ( a2-- )
  {
    if ( ((int (__fastcall *)(int))loc_D5EC)(a1) == 1 )
      return 0;
  }
  return -1;
}

//----- (0000DC6A) --------------------------------------------------------
int __fastcall sub_DC6A(unsigned __int8 a1)
{
  sub_D660(a1);
  return 0;
}

// nfuncs=178 queued=174 decompiled=174 lumina nreq=0 worse=0 better=0
// ALL OK, 174 function(s) have been successfully decompiled
